(() => {
 const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
 const permissions=[['menus','Menus','Arrange tabs and add shortcuts'],['dashboards','Dashboards','Configure home page blocks'],['content','Learning content','Create and edit lesson drafts'],['publish','Publishing','Publish changes in assigned areas'],['access','Access management','Manage groups, rights, and memberships']];
 async function mount(root,cloud){
  let groups=[],members=[],accounts=[],selected=null,busy=false;
  const message=(s,error=false)=>{const p=root.querySelector('[role="status"]');if(p){p.textContent=s;p.className=error?'status error':'status success';}};
  async function load(){
   const results=await Promise.all([cloud.from('site_groups').select('*').order('name'),cloud.from('site_group_members').select('group_id,user_id'),cloud.rpc('site_account_directory')]);
   for(const r of results)if(r.error)throw r.error;
   [groups,members,accounts]=results.map(r=>r.data||[]);if(!groups.some(g=>g.id===selected))selected=groups[0]?.id||null;
  }
  function render(){
   if(!root.isConnected)return;
   const group=groups.find(g=>g.id===selected),assigned=members.filter(m=>m.group_id===selected),ids=new Set(assigned.map(m=>m.user_id));
   root.innerHTML=`<div class="editor-head"><div><h2>Users & groups</h2><p>Assign administrative rights by component. Access changes take effect immediately.</p></div></div><section class="editor-card"><h3>Site owners</h3><p class="hint">Owners have all administrative rights. Group changes cannot remove their access.</p>${accounts.filter(a=>a.owner).map(a=>`<p class="owner-row">${esc(a.email)} <span class="permission-pill">Full administration</span></p>`).join('')}</section><div class="access-layout"><section class="editor-card"><h3>Groups</h3><div class="group-list">${groups.map(g=>`<button data-group="${g.id}" class="${g.id===selected?'selected':''}">${esc(g.name)}<small>${members.filter(m=>m.group_id===g.id).length} members</small></button>`).join('')}</div><form id="createGroup" class="stack"><label>New group name<input name="name" maxlength="80" required></label><button>Create group</button></form></section><section class="editor-card">${group?`<form id="groupRights" class="stack"><h3>Group rights</h3><label>Group name<input name="name" value="${esc(group.name)}" maxlength="80" required></label><div class="permission-matrix">${permissions.map(([id,label,description])=>`<label class="permission-row"><input type="checkbox" name="${id}" ${group.rights.includes(id)?'checked':''}><span><strong>${label}</strong><small>${description}</small></span></label>`).join('')}</div><p class="hint">Publishing also requires the right for the area being published. Access management allows granting any group right.</p><button class="primary">Save group rights</button></form><hr><h3>Members</h3>${assigned.length?assigned.map(m=>`<div class="member-row"><span>${esc(accounts.find(a=>a.user_id===m.user_id)?.email||m.user_id)}</span><button data-remove-member="${m.user_id}">Remove</button></div>`).join(''):'<p class="hint">No members yet. This group does not grant access to anyone.</p>'}<form id="addMember" class="stack"><label>Add a verified account<select name="user" required><option value="">Choose an account</option>${accounts.filter(a=>!ids.has(a.user_id)).map(a=>`<option value="${a.user_id}">${esc(a.email)}</option>`).join('')}</select></label><button>Add to group</button></form><p class="hint">Only accounts that have confirmed their email appear here. Memberships never grant access to private learner progress or Tutor conversations.</p>`:'<h3>Create your first group</h3><p>Choose a name, then assign its rights and members.</p>'}</section></div><p role="status" class="status"></p>`;
   root.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{selected=b.dataset.group;render();});
   root.querySelector('#createGroup').onsubmit=e=>{e.preventDefault();const name=e.currentTarget.elements.name.value.trim();run(async()=>{const r=await cloud.from('site_groups').insert({name,rights:[]}).select('id').single();if(r.error)throw r.error;selected=r.data.id;},'Group created. Add rights and members to enable access.');};
   root.querySelector('#groupRights')?.addEventListener('submit',e=>{
    e.preventDefault();const f=e.currentTarget,rights=permissions.filter(([id])=>f.elements.namedItem(id).checked).map(([id])=>id),name=f.elements.name.value.trim();
    if(!confirm(`Apply these rights immediately to all members of ${name}?${rights.includes('access')?' Access management lets them grant administrative rights to other accounts.':''}`))return;
    run(async()=>{const r=await cloud.from('site_groups').update({name,rights,version:group.version+1}).eq('id',group.id).eq('version',group.version).select('id');if(r.error)throw r.error;if(!r.data?.length)throw new Error('Group changed or your access was removed. Reload before trying again.');},'Group rights updated.');
   });
   root.querySelector('#addMember')?.addEventListener('submit',e=>{e.preventDefault();const id=e.currentTarget.elements.user.value;const account=accounts.find(a=>a.user_id===id);if(!account||!confirm(`Give ${account.email} the rights assigned to ${group.name}?`))return;run(async()=>{const r=await cloud.from('site_group_members').insert({group_id:selected,user_id:id});if(r.error)throw r.error;},'Member added.');});
   root.querySelectorAll('[data-remove-member]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this membership? Rights from other groups and owner access are retained.'))return;run(async()=>{const r=await cloud.from('site_group_members').delete().eq('group_id',selected).eq('user_id',b.dataset.removeMember);if(r.error)throw r.error;},'Membership removed.');});
  }
  async function run(fn,success){if(busy)return;busy=true;root.querySelectorAll('button,input,select').forEach(b=>b.disabled=true);message('Saving…');try{await fn();await load();render();message(success);}catch(e){message(e.message,true);}finally{busy=false;root.querySelectorAll('button,input,select').forEach(b=>b.disabled=false);}}
  root.innerHTML='<p role="status">Loading groups and permissions…</p>';
  try{await load();render();}catch(e){root.innerHTML='<p role="status"></p><button id="retryGroups">Retry</button>';message(e.message,true);root.querySelector('button').onclick=()=>mount(root,cloud);}
 }
 window.ChemAtlasAccess={mount};
})();
