const {JSDOM}=require('jsdom'),fs=require('fs'),assert=require('assert/strict');
const base=require('path').resolve(__dirname,'..')+'/';
const dom=new JSDOM('<body><aside class="sidebar"><div class="brand"></div><div class="nav-list"></div></aside><section id="homeView"></section></body>',{url:'https://example.test/dashboard',runScripts:'outside-only',pretendToBeVisual:true});
const w=dom.window,d=w.document,errors=[];w.addEventListener('error',e=>errors.push(e.error));w.scrollTo=()=>{};
w.CHEMATLAS_CONFIG={supabaseUrl:'https://test.invalid',supabasePublishableKey:'public'};
w.fetch=async()=>({ok:true,json:async()=>[{key:'navigation',payload:{items:[{id:'custom-organic',label:'Organic shortcut',route:'/organic'}]}},{key:'dashboard',payload:{columns:1,blocks:[{id:'custom-welcome',type:'text',label:'Hello',body:'<script>unsafe</script>',width:'full'},{id:'recent',label:'Recent activity',hidden:true,width:'half'},{id:'continue',label:'Continue learning',width:'full'}]}}]});
(async()=>{for(const f of ['data/genchem.js','content-store.js'])w.eval(fs.readFileSync(base+f,'utf8'));await w.ChemAtlasContent.ready;w.eval(fs.readFileSync(base+'chematlas-tutoring.js','utf8'));await new Promise(r=>setTimeout(r,150));
assert.equal(d.querySelector('.ca-configured-dashboard').dataset.columns,'1');assert.equal(d.querySelector('.ca-configured-dashboard').firstElementChild.textContent,'Hello<script>unsafe</script>');assert(d.querySelector('.ca-continue'));assert(d.querySelector('.ca-recent').hidden);assert.equal(d.querySelectorAll('script').length,0);assert.equal(d.querySelectorAll('.ca-tutoring-nav-group button').length,7);d.querySelector('[data-custom-nav]').click();assert.equal(w.location.pathname,'/organic');
await new Promise(r=>setTimeout(r,80));assert.equal(d.querySelectorAll('.ca-configured-dashboard').length,1);assert.equal(errors.length,0,errors.map(String).join('\n'));console.log('PASS: published dashboard ordering, safe custom text, retained learning widget, hidden optional widget, custom menu routing, stable rerender.');process.exit(0);})().catch(e=>{console.error(e);process.exit(1)});
